service: serverless-neuralnetwork
frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: python3.9
  region: ap-south-1
  httpApi:
    cors: true
  environment:
    URL_DB: ${env:URL_DB}

package:
  patterns:
    - "!.vscode/**"
    - "!node_modules/**"
    - "!notebooks/**"
    - "!data/**"
    - "!.env"
    - "!README.md"
    - "!package.json"
    - "!package-lock.json"
    - "!requirements.txt"

custom:
  pythonRequirements:
    dockerizePip: true

useDotenv: true

plugins:
  - serverless-python-requirements


functions:
  save_datapoint:
    handler: src.controllers.handlers.save_datapoint
    events:
      - httpApi:
          path: /datapoint
          method: post

  train:
    handler: src.controllers.handlers.train
    timeout: 900
    events:
      - httpApi:
          path: /train
          method: post

  infer:
    handler: src.controllers.handlers.infer
    events:
      - httpApi:
          path: /infer
          method: post
